// <auto-generated />
namespace MusicRater.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202007302045139_newtables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
